### ISSUE TITLE
I think the web.config is screwing things up

### ISSUE THREAD

**Issue by aarongustafson** [LittleBigThing/global-warning#1]
Getting a 404 on https://global-warning-10kapart2016.azurewebsites.net/

If I follow your rewrite, and do https://global-warning-10kapart2016.azurewebsites.net/index, it loads the page and 404s everything else.

**Comment by LittleBigThing** [comment]
Thanks Aaron.
I have fixed it I hope. I removed the rewrite from web.config completely, fixed some links and the content for <title> tag. I have requested an update yesterday, but it's not yet happened. Could you please update from the repo? Many thanks!!

**Comment by aarongustafson** [comment]
Yay! https://global-warning-10kapart2016.azurewebsites.net/

**Comment by LittleBigThing** [comment]
Yay it is!!! 🙂
Thank you!!!
